### ISSUE TITLE
Update to new version of Identity

### ISSUE THREAD

**Issue by mesuttalebi** [mrahhal/MR.AspNet.Identity.EntityFramework6#10]
Hello, there is some new improvements to Identity, please update your project use to the latest version of the identity.

**Comment by mrahhal** [comment]
Hello, if you're talking about version 2.0.0-preview1 then I don't have any immediate plans to support that (might do that if there are enough requests). I do plan on supporting the final release though.

**Comment by maganuk** [comment]
Hello, Final release is out. Any plan of porting this to support netstandard20?

**Comment by mrahhal** [comment]
Hello. I plan on doing that very soon. But I'm not sure about targeting `netstandard20`, I'm pretty sure EF6 will need to target `net461` for me to be able to do that.

**Comment by maganuk** [comment]
My bad, I forgot there is a DBContext in there. Thought it was just pocos.

**Comment by mrahhal** [comment]
In theory, I can target `netstandard2.0` using the new compatibility feature of .net 2.0. But it won't have much benefit since the consumer will need to target full .net for EF6 to work anyway.

**Comment by maganuk** [comment]
Might be helpful in case they plan on adding support for netstandard in 6.3 

Have a look [here](https://github.com/aspnet/EntityFramework6/issues/271)

Though I have my doubts it'll ever happen

**Comment by mrahhal** [comment]
Ah interesting. I also doubt it'll happen, seeing that EF6 remained completely without a dotnet tool for a few months when .net core was first released, while pushing people to use EFCore. I don't think they'll ever plan on giving EF6 more space than what it occupies now.

**Comment by maganuk** [comment]
I totally agree. Offtopic but does ef6 have a tool now? other than the Migrator tool that you very kindly developed?

**Comment by mrahhal** [comment]
Nope, there isn't. Whether it is because Migrator.EF6 had filled that gap or they just didn't plan on creating one for EF6, not sure. I think you can use "migrator.exe" directly.. but who would want to do that. When this all started it was said that the new project system (after project.json) will work with the EF6 powershell tools. Haven't had the time to check, but I really prefer the handy `dotnet ef` much more anyway.

**Comment by maganuk** [comment]
Yup dotnet ef is great if youre using ef core. But there are still some serious issues with EF core, which is why many people (including me) still prefer to use EF6.

I've opened so many issues (re. ef core) and they propose the silliest of workarounds. Long way for ef core to go before it catches up with EF6.

**Comment by mrahhal** [comment]
Indeed. I've long since lost hope for EFCore. At its current stage, it's perfect for small scale packages (ex IdentityServer), but not at all for enterprise level apps. In the future? Maybe.

**Comment by mrahhal** [comment]
Please try `v3.0.0` and let me know if you face any problems. Haven't had enough time to test it thoroughly.
