### ISSUE TITLE
IdentityUser constructor should initialize the Tokens property

### ISSUE THREAD

**Issue by ckalan** [mrahhal/MR.AspNet.Identity.EntityFramework6#18]
Tokens property in IdentityUser is read-only and not initialized. This throws NullReference errors and also "Property does not have a setter" error during UserManager.SetAuthenticationToken method

**Comment by mrahhal** [comment]
I don't believe this is the problem you're facing. All other list properties inside `IdentityUser` are navigational properties, and all of them are not initialized. (Sure, I would probably initialize those if this was in my business app, because it's a domain model, but this isn't the problem)

The `UserManager` calls the store's `SetTokenAsync`, which never references this property. It just directly adds a token entity to the context.

So I'm not sure why you're getting a nullref inside UserManager.SetAuthenticatonToken. Do you have a stack trace?

---

EDIT (take the text above with a grain of salt):

Again, not sure how that's directly related to a nullref here. But I see some places I'm initializing all of those except for `Tokens`. I'll just centralize this and initialize those props as I would usually do.

**Comment by mrahhal** [comment]
@ckalan If the problem persists in `3.0.6` please reopen the issue.

**Comment by ckalan** [comment]
I am not sure as well but below workaround fixed the issue. I guess EF was trying to add an entity to the collection but since it is null, it tries to initialize the collection first. 

```
public class User : IdentityUserInt
    {
        private readonly List<IdentityUserTokenInt> _tokens = new List<IdentityUserTokenInt>();

        public override ICollection<IdentityUserTokenInt> Tokens => _tokens;
    }
```
